Server:
  Mode: release
  Port: 8800

Database:
  Host:
  Port: 3306
  UserName:
  Password:
  Database: distriai_index_solana

Redis:
  Addr: 'localhost:6379'
  Password:
  DB: 0

Mailbox:
  Host:
  Port: 25
  Username:
  Password:

Aws:
  Region:
  AccessKeyId:
  SecretAccessKey:

Chain:
  Rpc: 'https://api.devnet.solana.com'
  Ws: 'wss://api.devnet.solana.com'
  ProgramId: 6yFTDdiS1W9T9yg6YejkwKggkEE4NYqdSSzVqQvuLn16
  FaucetPrivateKey:
  Dist: 2mdavGYoNKKYVx4RvM36pPH6MJ1hr6TjkkcdFzCcpFZR
  DistDecimals: 9
  DistFaucetAmount: 5
