Server:
  Mode: release
  Port: 8800

Database:
  Host:
  Port: 3306
  UserName:
  Password:
  Database: distriai_index_solana

Mailbox:
  Host:
  Port: 25
  Username:
  Password:

Chain:
  Rpc:
  ProgramId: HF4aT6sho2zTySB8nEeN5ThMvDGtGVRrH3jeBvxFNxit
  FaucetPrivateKey:
  Dist: 896KfVVY6VRGQs1d9CKLnKUEgXXCCJcEEg7LwSK84vWE
  DistDecimals: 9
  DistFaucetAmount: 5
